application: leader-board
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /fonts
  static_dir: fonts

- url: /api/.*
  script: api.py

- url: /.*
  script: web.py

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

